language: python

sudo: required

python:
  - "3"
  - "2"
  - "pypy"
  - "pypy3"
  
include:
  - os: linux
    node_js: '7'
    
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  
cache:
  directories:
    - $HOME/.cache/pip
  
addons:
  chrome: stable
  sauce_connect: true
  
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
  
install:
  - sudo apt-get install xvfb
  - sudo apt-get update
  - pip show setuptools
  - pip install -r requirements.txt
  
  - wget -N http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - sudo rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  
script:
  - cd Web-automationg
  - behave
#   - behave Second_web_demo  
#   - sleep 10
  - behave android_behave
