language: Python

sudo: required

python:
  - "3.6"
  - "2.7"
  - "3.5"
  - "pypy"
  - "pypy3"
  - "3.7-dev"
  
include:
  - os: linux
    node_js: '7'
    
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  
cache:
  directories:
    - $HOME/.cache/pip
  
addons:
  chrome: stable
  sauce_connect: true
  
env:
  global:
#     - secure: L/aGHl+XZ2tyeZ0xZTkKPySfsVZxkQt9Y3naN0icMu8DoXP83eUQ/gKooEKP0i0XTvwslCGa808UyZ99mWAdZ/WBA23i7q3fCLHwMcA7EcRsDky8vv6nMu00jTwLEX2ly+3+jc4xZV7ZO7KJNBRBcSD78L2KiMiRUzZ+WFZVrZ0=
#     - secure: T9Ur8o93Bs42r2De53U97oheh/E+P9VDpuRYHUtr5YoxU/n4sALcz3FfyJ6HOcuDctIXb26MvNrzvf9abaxNFf4QapqVlWW6Fj8xHA9x55eRjz4QasyM1nk7gqhlZ2HZuvxqhEcgvfirn7FGb9bIEuBVmFaJtqURp2JwEO4ABdQ=

    - username: "xolanimxoxozi"
    - access_key: "3bd6fd59-45ea-4b29-9c9c-6c5b0710caae"
    
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
  
install:
  - sudo apt-get install xvfb
  - sudo apt-get update
  - pip show setuptools
  
  - pip install git+https://github.com/behave/behave
  - pip install toolium
  - pip install sauceclient
  
  - wget -N http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - sudo rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  
script:
  - cd Web-automating
  - behave
#   - behave Second_web_demo  
#   - sleep 10
#   - behave android_behave
